name: Upload PGNs to Lichess Study

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run upload script
        run: python -u upload.py
